# Unique name for this workflow
name: "[PUSH] Create Package"

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "force-app/**"

# Jobs to be executed
jobs:
  create-package:
    name: Create new package
    runs-on: ubuntu-latest
    steps:
      # Install SFDX
      - name: Install SFDX
        uses: sfdx-actions/setup-sfdx@v1

      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v2

      # Authenticate prod
      - name: Authenticate prod
        run: |
          echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt
          sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d
          rm -f ./PROD_SFDX_URL.txt

      # Authenticate integration-sandbox
      - name: Authenticate prod
        run: |
          echo ${{ secrets.INTEGRATION_SANDBOX_SFDX_URL}} > ./INTEGRATION_SANDBOX_SFDX_URL.txt
          sfdx force:auth:sfdxurl:store -f ./INTEGRATION_SANDBOX_SFDX_URL.txt -a integration-sandbox -s
          rm -f ./INTEGRATION_SANDBOX_SFDX_URL.txt

      # Delete unpackagable
      - name: "Delete unpackagable"
        run: |
          rm -rf ./unpackagable
          rm -rf ./force-app/unpackagable

      # Create package version
      - name: "Create package version"
        id: package-version-create
        run: |
          sfdx force:package:version:create -f config/project-scratch-def.json -p $(cat sfdx-project.json | jq '.packageDirectories[0].package' -r) -k ${{ secrets.PACKAGE_KEY }} -w 90 --json | tee output
          echo "::set-output name=result::$(cat output | jq -c .)"

          status=$(cat output |jq '.status')
          if [ $status == "0" ]
          then
            echo "::set-output name=isSuccess::true"
          fi
          rm output

      # Extract data from package version create result
      - name: "Extract package:version:create result data"
        id: extract-data-package-version-create
        uses: muenzpraeger/github-action-extract-sfdx-packaging-result@master
        with:
          json: ${{steps.package-version-create.outputs.result}}

      # Install new package version into integration org
      - name: "Install new package version into integration org"
        id: integration-installation
        run: |
          sfdx force:package:install --package ${{ steps.extract-data-package-version-create.outputs.packageVersionId }} -w 20 -b 20 -u integration-sandbox -r -k ${{ secrets.PACKAGE_KEY }} --json | tee output

          status=$(cat output |jq '.status')

          if [ $status == "0" ]
          then
            echo "::set-output name=isSuccess::true"
          fi
          rm output

      # set release variables
      - name: "Set release fields"
        if: success() || (failure() && steps.package-version-create.outputs.isSuccess && steps.extract-data-package-version-create.outputs.isSuccess )
        id: release-fields
        run: |
          versionNumber=$(cat sfdx-project.json | jq '.packageDirectories[0].versionNumber' -r | sed 's/.\{5\}$//')
          packageAliases=$(cat sfdx-project.json | jq '.packageAliases | keys_unsorted[-1]' -r | sed 's/.*-//')

          echo "::set-output name=tagName::v$(echo $versionNumber)-beta$(echo $packageAliases)"
          echo "::set-output name=releaseName::$(echo $versionNumber)-beta$(echo $packageAliases)"
          echo "::set-output name=bodyVersion::$(echo $versionNumber).$(echo $packageAliases)"
          echo "::set-output name=bodyPackage::${{ steps.extract-data-package-version-create.outputs.packageVersionId }}"

          echo "::set-output name=packageCreation::✅ Package Creation"

          if [ ${{ steps.integration-installation.outputs.isSuccess }} == "true" ]
          then
            echo "::set-output name=integrationInstallation::✅ Package Installation (Integration Sandbox)"
          else
            echo "::set-output name=integrationInstallation::❌ Package Installation (Integration Sandbox)"
          fi

      # Generate changelog from commits
      - name: Generate changelog
        if: success() || (failure() && steps.package-version-create.outputs.isSuccess && steps.extract-data-package-version-create.outputs.isSuccess )
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.3
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      # create github release
      - name: "Create Release"
        if: success() || (failure() && steps.package-version-create.outputs.isSuccess && steps.extract-data-package-version-create.outputs.isSuccess )
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-fields.outputs.tagName }}
          release_name: ${{ steps.release-fields.outputs.releaseName }}
          body: |
            **Version**: ${{ steps.release-fields.outputs.bodyVersion }}
            **Package ID**: ${{ steps.release-fields.outputs.bodyPackage }}
            **Author**: ${{ github.actor }}

            ${{ steps.release-fields.outputs.packageCreation }}
            ${{ steps.release-fields.outputs.integrationInstallation }}

            ## Changelog

            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true

  check-code-coverage:
    name: Check Code Coverage
    runs-on: ubuntu-latest
    steps:
      # Check if secret for code coverage exists
      - name: Check if secret for code coverage exists
        id: secretChecker
        run: |
          if ["${{ secrets.CODECOV_TOKEN }}" != ""]; then
            echo "::set-output name=shouldContinue::true"
            echo "Code coverage secrets exists for this repo, so process continues"
          else
            echo "Code coverage secrets does NOT exist for this repo, aborting"
          fi

      # Install SFDX
      - name: Install SFDX
        if: steps.secretChecker.outputs.shouldContinue
        uses: sfdx-actions/setup-sfdx@v1

      # Checkout the code in the pull request
      - name: "Checkout source code"
        if: steps.secretChecker.outputs.shouldContinue
        uses: actions/checkout@v2

      # Authenticate prod
      - name: Authenticate prod
        if: steps.secretChecker.outputs.shouldContinue
        run: |
          echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt
          sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d
          rm -f ./PROD_SFDX_URL.txt

      # Create scratch org
      - name: "Create scratch org"
        if: steps.secretChecker.outputs.shouldContinue
        id: createScratchOrg
        run: |
          sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 --json | tee output

          status=$(cat output |jq '.status')
          if [ $status == "0" ]
          then
            echo "::set-output name=isSuccess::true"
          else
            exit 125
          fi
          rm output

      # Install sfpowerkit plugin used to install multiple packages only by version number
      - name: "Install sfpowerkit plugin"
        if: steps.secretChecker.outputs.shouldContinue
        run: "echo y | sfdx plugins:install sfpowerkit"

      # Get package keys
      - name: "Get package keys"
        if: steps.secretChecker.outputs.shouldContinue
        id: install-keys
        run: |
          keys=""
          for p in $(jq '.result | .[].Name' -r <<< "$(sfdx force:package:list --json)"); do
              keys+=$p":${{ secrets.PACKAGE_KEY }} "
          done

          echo "::set-output name=keys::$(echo $keys)"

      # Install packages this repo is dependant on
      - name: "Install dependant packages"
        if: steps.secretChecker.outputs.shouldContinue
        run: "sfdx sfpowerkit:package:dependencies:install -u scratch-org -r -a -w 60 -k '${{ steps.install-keys.outputs.keys }}'"

      # Deploy source to scratch org
      - name: "Push source to scratch org"
        if: steps.secretChecker.outputs.shouldContinue
        run: "sfdx force:source:push"

      # Sleep for 1 minute while permset groups are updating
      - name: Sleep for 1 minute while permset groups are updating
        if: steps.secretChecker.outputs.shouldContinue
        uses: jakejarvis/wait-action@master
        with:
          time: "1m"

      # Run Apex tests in scratch org
      - name: "Run Apex tests"
        if: steps.secretChecker.outputs.shouldContinue
        run: "sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20"

      # Upload code coverage data
      - name: "Upload code coverage for Apex to Codecov.io"
        if: steps.secretChecker.outputs.shouldContinue
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Remove test result files
      - name: "Remove test result files"
        if: steps.secretChecker.outputs.shouldContinue
        run: rm -rf ./tests

      # Housekeeping
      - name: "Delete scratch org"
        if: always() && steps.createScratchOrg.outputs.isSuccess
        run: "sfdx force:org:delete -p -u scratch-org"
